add parsing from sql to dynamo where clause
Pepperi-Addons/pepperi-filters pull request #12
Opened 2022-03-30 12:42 UTC by nofarpepperi

2022-03-30 16:04 UTC, Chasky-H requested changes

2022-03-30 16:04 UTC, Chasky-H commented on filters/string-filter.ts
> +                res.Count = count;
It seems like this can be refactoring into a helper function, or at least part of it.

2022-03-31 09:25 UTC, nofarpepperi commented on filters/filter.ts
> +    abstract toDynamoWhereClause(letterForMark: string, expressionAttributeNames: any, expressionAttributeValues: any, count: number) : DynamoResultObject;
changed to toDynamoDBQuery

2022-03-31 09:25 UTC, nofarpepperi commented on filters/filter-collection.ts
> +            var DynamoWhereClause = filter.toDynamoWhereClause(letterForMark, expressionAttributeNames, expressionAttributeValues, count);
fixed

2022-03-31 09:25 UTC, nofarpepperi commented on filters/filter-factory.ts
> +
fixed

2022-03-31 09:26 UTC, nofarpepperi commented on index.ts
> +export function toDynamoQuery(jsonFilter: JSONFilter | undefined, letterForMark: string, expressionAttributeNames: any, expressionAttributeValues: any, count: number): DynamoResultObject {
fixed

2022-03-31 09:26 UTC, nofarpepperi commented on filters/string-filter.ts
> +                res.Count = count;
fixed

2022-04-03 13:11 UTC, Chasky-H approved these changes

2022-04-04 08:40 UTC, merged