DI-25635-handle smart filters multipleStringValues
Pepperi-Addons/pepperi-filters pull request #37
Opened 2023-11-06 12:35 UTC by MayTetro1

2023-11-06 13:12 UTC, roiaharon-pepperi requested changes

2023-11-06 13:12 UTC, roiaharon-pepperi commented on ngx-filters/ngx-to-json/metadata.ts
> +export declare type SchemeFieldType = (typeof SchemeFieldTypes)[number];
why have you changed it? are you sure it's working?

2023-11-06 13:12 UTC, roiaharon-pepperi commented on filters/string-filter.ts
> +    toSQLWhereClause(): any {
why changing the return type?

2023-11-06 13:12 UTC, roiaharon-pepperi commented on filters/string-filter.ts
> +                return `${this.apiName} IN '${this.filterValues[0]}'`;
when it comes to 'In' operator, there could be more than 1 value, you can't ignore the rest

2023-11-12 07:45 UTC, Chasky-H approved these changes

2023-11-12 08:24 UTC, merged